### ISSUE TITLE
`\vec{}` and `\sqrt{}` do not render with the given KaTeX example code

### ISSUE THREAD

**Issue by StevenClontz** [ssssota/svelte-exmarkdown#123]
If you try to add a vector or square root at https://ssssota.github.io/svelte-exmarkdown/docs/08-math-formula using `\vec` or `\sqrt`, the math is not typeset with an arrow or square root symbol.

**Comment by ssssota** [comment]
Thank you for the report!

I have confirmed the bug!
SVG does not seem to be rendering.

**Comment by StevenClontz** [comment]
A possible hint: when our page https://scholarlattice.pi-base.org/markdown is loaded, you see the square root for a brief moment before it disappears.

**Comment by StevenClontz** [comment]
Is there a solution here? https://github.com/sveltejs/svelte/issues/7613

**Comment by ssssota** [comment]
Sorry for the delay in responding.
A fixed version has been released!
https://github.com/ssssota/svelte-exmarkdown/releases/tag/v3.0.3

**Comment by StevenClontz** [comment]
Thanks so much. I can confirm fixes `\sqrt` rendering at https://scholarlattice.pi-base.org/markdown

I'm still dealing with `\vec` rendering not appearing on that page. However, `\vec` looks fine when I try it at https://ssssota.github.io/svelte-exmarkdown/docs/08-math-formula So I assume it's a bug in my CSS or similar, and not an issue here.

Thanks again!
