### ISSUE TITLE
ERR_REQUIRE_ESM error on netlify

### ISSUE THREAD

**Issue by useiichi** [ssssota/svelte-exmarkdown#15]
現時点で最新のsveltekitのバージョンで本サンプルを作成してnetlifyにデプロイすると下記エラーになってしまいます。

500
require() of ES Module /var/task/node_modules/remark-parse/index.js from /var/task/.netlify/server/entries/pages/index.svelte.js not supported.
Instead change the require of index.js in /var/task/.netlify/server/entries/pages/index.svelte.js to a dynamic import() which is available in all CommonJS modules.
Error [ERR_REQUIRE_ESM]: require() of ES Module /var/task/node_modules/remark-parse/index.js from /var/task/.netlify/server/entries/pages/index.svelte.js not supported.
Instead change the require of index.js in /var/task/.netlify/server/entries/pages/index.svelte.js to a dynamic import() which is available in all CommonJS modules.

**Comment by ssssota** [comment]
Issueありがとうございます！

- https://github.com/ssssota/svelte-exmarkdown-netlify-test
- https://svelte-exmarkdown-netlify-test.netlify.app/

雑にデプロイしてみたところ、特に設定せずに動いてしまって
可能でしたら再現環境をご用意いただけますか？

**Comment by useiichi** [comment]
ありがとうございます。
svelte-exmarkdown-netlify-testを私の方でnetlifyにデプロイしましたところ、動くことを確認しました。
エラーが発生しているレポジトリはこちらです。
https://github.com/useiichi/my-app
https://delicate-tulumba-808aed.netlify.app/
package.jsonのviteなどのバージョンが異なるようですが、
私は普通に
npm create svelte@latest my-app
で作成しております。

**Comment by ssssota** [comment]
SSRを選択したところ ([該当commit](https://github.com/ssssota/svelte-exmarkdown-netlify-test/commit/01faaa107d275bade1b95e0949adbaf2f6bddec4)) 同様の現象を確認できました :pray:

**Comment by ssssota** [comment]
https://github.com/ssssota/svelte-exmarkdown-netlify-test/pull/4

このブランチを見ていただくとわかるかもですが、svelte-exmarkdown内部で使っている `unified` や `remark-parse` がVite+Netlifyの相性と悪いように見えます

**Comment by ssssota** [comment]
https://github.com/ssssota/svelte-exmarkdown-netlify-test/pull/5

一応、SSRの出力をCommonJSにすることで動作させることができました。

Viteの [`ssr.format`](https://vitejs.dev/config/ssr-options.html#ssr-format) というオプションを有効にすることで対応できましたがVite的には非推奨になってます

**Comment by ssssota** [comment]
Netlifyに関してはssr.formatをcjsにするのが他ライブラリに関してもベターと言えそうです。
こちらの問題に関しては本ライブラリの問題ではないのでクローズさせていただきます :bow:
