### ISSUE TITLE
Emoji Support

### ISSUE THREAD

**Issue by JonLangfordUK** [ssssota/svelte-exmarkdown#255]
Hello 👋 
Does your markdown solution support emojis?
Out of the box, it seems that it doesn't pick up on typed emoji like this:
:)
:(
:'(
:P

If not, is there a plugin that I could look into that would work well with your awesome project? 😄

**Comment by ssssota** [comment]
You can use [`remark-emoji`](https://www.npmjs.com/package/remark-emoji).

Demo: https://stackblitz.com/edit/svelte-exmarkdown-emoji?file=src%2FApp.svelte&terminal=dev
