### ISSUE TITLE
RehypeRaw is incompatible with RehypeSlug

### ISSUE THREAD

**Issue by OrangeBurrito** [ssssota/svelte-exmarkdown#259]
As the title says. If the rehypeRaw plugin is added (in order to use GFM), it works fine until you use the rehypeSlug plugin, in which case the inline HTML is not properly rendered. They work separately.

**Comment by ssssota** [comment]
I think it works fine.
https://stackblitz.com/edit/svelte-exmarkdown-rehype-slug?file=src%2FApp.svelte&terminal=dev

Please share reproduction sample!
