### ISSUE TITLE
Children.svelte is missing from library

### ISSUE THREAD

**Issue by hgoona** [ssssota/svelte-exmarkdown#262]
For some reason, when I upgraded to the latest version of svelte-exmarkdown I no longer see this file in the library:
![image](https://github.com/user-attachments/assets/ee53151c-1eab-4973-b830-7667e53a53d4)
I was previously using it like this:
![image](https://github.com/user-attachments/assets/e358eae2-e444-470e-9449-d9c548295411)

Has this changed??

**Comment by ssssota** [comment]
It has removed from v3!

Please check the migration guide: https://github.com/ssssota/svelte-exmarkdown/releases/tag/v3.0.0
