### ISSUE TITLE
How to use remark frontmatter with svelte-exmarkdown

### ISSUE THREAD

**Issue by projectashik** [ssssota/svelte-exmarkdown#27]
I'm trying to use the remark frontmatter with the svelte-exmarkdown, but it's not working.

**Comment by ssssota** [comment]
You can use like this:

```html
<script lang="ts">
  import Markdown from 'svelte-exmarkdown';
  import remarkFrontmatter from 'remark-frontmatter';
  const plugins = [
    { remarkPlugin: [remarkFrontmatter, ['yaml']] },
  ];
  let md = `\
---
title: test
---

# Hello`;
</script>

<textarea bind:value={md} />

<Markdown {md} {plugins} />
```


However, svelte-exmarkdown can't expose frontmatter data. The above example can only be rendered ignoring Frontmatter.
If you want to use frontmatter data, you should use another package such as [front-matter](https://www.npmjs.com/package/front-matter) together.
