### ISSUE TITLE
How we can render html tags and custom tags 

### ISSUE THREAD

**Issue by projectashik** [ssssota/svelte-exmarkdown#28]
I am trying to add support of html tags inside markdown but haven't found any working solution yet.
And I also want to render the custom tags.

**Comment by ssssota** [comment]
> I am trying to add support of html tags inside markdown but haven't found any working solution yet.

Oh, yes. It certainly doesn't seem to be supported yet.
I'll try to support it!

> And I also want to render the custom tags.

You want to support custom tags in Markdown? More specific examples would be helpful!

**Comment by AgarwalPragy** [comment]
Can you help me understand what I'm doing wrong?

updated to 2.0.0, added `rehype-raw` and ran `pnpm install`.
```json
    "rehype-raw": "^6.1.1",
    "svelte-exmarkdown": "^2.0.0",
```

Added a plugin
```ts
import type { Plugin } from 'svelte-exmarkdown'
import rehypeRaw from 'rehype-raw'

export const MARKDOWN_PLUGINS: Plugin[] = [
  { rehypePlugin: rehypeRaw },
  ...
]
```
```html
<Markdown {md} plugins={MARKDOWN_PLUGINS} />
```

It still strips off all the HTML tags from the following content
```html
<b>Hello</b>, <span class="text-secondary-500">world</span>!
```

**Comment by ssssota** [comment]
Hmm. I don't see why it wouldn't work.
Maybe there is a problem with the order of the plugins.

Please check this demo: https://stackblitz.com/edit/svelte-exmarkdown-28-demo?file=src/App.svelte

**Comment by AgarwalPragy** [comment]
My bad. Seems like it was an issue on my side. 

I had to run the following to get it to work.

```
rm -rf node_modules
rm pnpm-lock.yaml
pnpm store prune
pnpm install
```

Weird that I had to bust the pnpm cache. 🤷

**Comment by ssssota** [comment]
> Also, do you know why the official Svelte REPL is unable to handle svelte-exmarkdown?

Sorry, I don't know. 🤔
