### ISSUE TITLE
Adding custom components

### ISSUE THREAD

**Issue by heyngra** [ssssota/svelte-exmarkdown#36]
Hey, I have a question, because I tried to implement it, but I can't figure it out. Is there any way, to add custom components to the svelte-exmarkdown?

Lets imagine we have h1 text called "Test". You would type it normally as 
```md
# Test
```

But is there a way to f.e add a button below, that acts like a svelte component, from the text itself?
For example
```md
# Test
<CustomButton/>
```
(So the user can type this and server can import these components if necessary)

**Comment by ssssota** [comment]
Thanks for your question!

You can implement like this: https://stackblitz.com/edit/svelte-exmarkdown-custom-component?file=src%2FApp.svelte

1. use `rehype-raw` module as rehypePlugin.
2. create your custom component.
3. create bridge component.

> **Warning**
> There are a few things to keep in mind.
> 
> - When setting up a renderer for a plugin, the keys must be all lowercase
> - Component properties must be lowercased as well
> - You cannot use *self-closing* syntax like `<CustomButton/>`

**Comment by jacoblukewood** [comment]
@ssssota is this still the optimal way to accomplish this? It seems like quite the workaround.

**Comment by ssssota** [comment]
@jacoblukewood Yes.
(From [svelte-exmarkdown v3](https://github.com/ssssota/svelte-exmarkdown/releases/tag/v3.0.0)), you don't need to create bridge component. 

New example is here!
https://stackblitz.com/edit/svelte-exmarkdown-custom-elemtents?file=src%2FApp.svelte&terminal=dev

---

> It seems like quite the workaround.

You are right. This way is powerful. _With great power comes great responsibility._
If you don't like it, you can use [MDsveX](https://mdsvex.pngwn.io/).
