### ISSUE TITLE
Using shiki for highlighting

### ISSUE THREAD

**Issue by vlrevolution** [ssssota/svelte-exmarkdown#50]
How could we use this package as the highlighter for the code blocks?

https://github.com/shikijs/shiki

Thanks so much for your hard work & valuable time.

**Comment by vlrevolution** [comment]
It was relatively easy by looking at the example of the playground you have created. Thanks :)

**Comment by shyakadavis** [comment]
Hi, @vlrevolution @ssssota 

I was trying to use Shiki, specifically Shikiji, but haven't figured it out.

Do you mind sharing a code snippet of how you achieved it?

Thank you.

P.S. It even has this rehype plugin. https://github.com/antfu/shikiji/tree/main/packages/rehype-shikiji

**Comment by ssssota** [comment]
Hi!

We can use `@shikijs/rehype`.
If you want to use it, you should use [rehypeShikiFromHighlighter](https://shiki.matsu.io/packages/rehype#fine-grained-bundle).

I'll close this issue, but you can re-open it!
Thank you.
