### ISSUE TITLE
How does it sanitize the output

### ISSUE THREAD

**Issue by vlrevolution** [ssssota/svelte-exmarkdown#51]
I think I'm going to give this package a try and am looking at the source code. Could you point out to me how it sanitizes the output?

**Comment by ssssota** [comment]
Thanks for your question!

This package performs sanitization by default.
You can try out it yourself from [here](https://ssssota.github.io/svelte-exmarkdown/).

**Comment by vlrevolution** [comment]
I'm curious though, which part sanitizes in the code? Just to broaden my knowledge of the subject

**Comment by ssssota** [comment]
This library is based on the [unified](https://github.com/unifiedjs/unified).

1. svelte-exmarkdown parse **markdown** to [**mdast**](https://github.com/syntax-tree/mdast) using [remark-parse](https://github.com/remarkjs/remark/blob/main/packages/remark-parse). (mdast means *"**M**ark**d**own **A**bstract **S**yntax **T**ree"*)
2. svelte-exmarkdown convert **mdast** to [**hast**](https://github.com/syntax-tree/hast) using [remark-rehype](https://github.com/remarkjs/remark-rehype). (hast means *"**H**TML **A**bstract **S**yntax **T**ree"*)
3. And svelte-exmarkdown render **HTML** from **hast** without [`{@html template}`](https://svelte.dev/docs#template-syntax-html). <- **This step also serves as a sanitization!**

In general, `{@html template}` syntax has XSS risks.
For example:

```html
<script>
  export let someUserInput = '<script' + '>alert()<' + '/script>';
</script>
{@html someUserInput}
```

**Comment by ssssota** [comment]
Render step code is [here](https://github.com/ssssota/svelte-exmarkdown/blob/516beedaccd77abff7ed9fa1c542c613430286c9/src/lib/renderer/Renderer.svelte).
There code traverse HAST and render HTML.

I am not good at English and my explanation may be inadequate.
If you do not understand well, please feel free to ask.

**Comment by vlrevolution** [comment]
Perfect explanation. Your english is not as bad as you think! Amazing
library..

**Comment by ssssota** [comment]
Thank you!
Close this issue if your problem is resolved :)
