### ISSUE TITLE
Any idea why this is happening?

### ISSUE THREAD

**Issue by vlrevolution** [ssssota/svelte-exmarkdown#53]
Working good, using two plugins, one for code blocks and one for tables and I'm seeing a lot of warnings in console:
![image](https://github.com/ssssota/svelte-exmarkdown/assets/67480746/5ac1f0b8-4296-4b2a-b351-1be556052016)

Any idea how this could happen?

**Comment by ssssota** [comment]
Please check #23 and #25 .

**Comment by vlrevolution** [comment]
What is the solution? I don't really understand what I should do. I am not using SvelteKit btw

**Comment by ssssota** [comment]
Oops, I'm sorry.
#17 & #18 are related issues.
You should write variables as props:

_MdTable.svelte_
```html
<script>
export let type = undefined;
export let tagname = undefined;
export let position = undefined;
export let __index = undefined;
// HACK: ignore `unused-export-let`
tagName && type && position && __index;

// And you code ...
</script>
```
